# fly.toml app configuration file generated for outlook-cleaner

app = "outlook-cleaner-app" # The user should change this to their unique app name
primary_region = "eze" # Change to closest region (e.g., eze for Buenos Aires)

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[mounts]]
  source = "outlook_data"
  destination = "/data"

[env]
  CACHE_FILE = "/data/token_cache.json"
